### ISSUE TITLE
Throw proper error message while tests fails

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/ocis-php-sdk#131]
Currently, error messages are not thrown if the integration test fails. Without an error message we have to debug more so i think proper messgae should be throen in some location in integration test

**Comment by S-Panta** [comment]
Most of the function we use inside the source code all has their `proper error message` when the request fails. 
`Assert` statement has its style of just throwing assert Error.

**Comment by S-Panta** [comment]
It would be good if the PR is made separately for each file inside the integration test to avoid more changes in a single PR.

- [ ] DriveTest
- [ ] GroupsTest
- [ ] NotificationTest
- [ ] OcisResoureceTest
- [ ] OcisTest
- [ ] ResoureceInviteTest
- [ ] ResourceShareLinkTest
- [ ] ShareCreatedModifyTest
- [ ] ShareGetSharedByMeTest
- [ ] ShareReceivedTest
- [ ] ShareTestGetSharedWithMeTest
- [ ] UsersTest

**Comment by S-Panta** [comment]
Once all this PR get merged, I'll check over all the integration test for coherent message.

**Comment by S-Panta** [comment]
Closing this PR as all is merged
