### ISSUE TITLE
run nightly tests

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis-php-sdk#153]
I think we should also run tests nightly to notice issues like https://github.com/owncloud/ocis/issues/8068 earlier

**Comment by amrita-shrestha** [comment]
I have added a cron job for now
Suggestion
- Run integration test on the master branch with the latest commit in the nightly build
- avoid test runs on the stable branch

**Comment by individual-it** [comment]
why avoiding test runs on the stable branch? that is the most important thing

**Comment by amrita-shrestha** [comment]
Sawjan Dai just now informed us that owncloud would backport bug fixes in stable branch so we should run nightly in stable-branch too with latest-commit id

**Comment by amrita-shrestha** [comment]
Remaing:
- [ ] Run it (blocked due to https://github.com/owncloud/ocis-php-sdk/issues/204)

**Comment by amrita-shrestha** [comment]
- [ ] cache ocis pipeline not triggered on nightly
