### ISSUE TITLE
add tests for guest users

### ISSUE THREAD

**Issue by phil-davis** [owncloud/ocis-php-sdk#197]
"guest" users in ocis are users that have the "User Light" role.
Probably the existing ocis-php-sdk can make use of users that have role "User Light", but we should test that.

- [ ] add tests for creating and deleting "User Light" users (maybe we can't do that?)
- [ ] add tests for sharing with "User Light" users

Adjust ocis-php-sdk as needed to make it work.
Report any blockers in libre-graph-api-php or ocis that prevent this from working.

**Comment by individual-it** [comment]
@micbar you have said that there are no guest-users yet in ocis. Can you share some light on this issue?

**Comment by individual-it** [comment]
closing for now
