### ISSUE TITLE
Release v1.0.0-rc2

### ISSUE THREAD

**Issue by phil-davis** [owncloud/ocis-php-sdk#206]
PR #198 fixed the spelling of public method `isClientSynchronized`
That is a backward-compatibility break, so it would be good to make a next release candidate, and we can update consumers (moodle integration) to use that.

(And whatever other changes have happened since RC1)

**Comment by individual-it** [comment]
#203 will in-cooperate changes that need to be done after https://github.com/owncloud/ocis/pull/8322 and then we can release a second RC version
