### ISSUE TITLE
Add support for drive root endpoint 

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/ocis-php-sdk#223]
New endpoint has been added on ocis : https://owncloud.dev/libre-graph-api/#/drives.root/InviteSpaceRoot
Add code to support root endpoint api

- [x] update libre graph package https://github.com/owncloud/ocis-php-sdk/pull/224
- [x] get permission https://github.com/owncloud/ocis-php-sdk/pull/225
     - [x] add code which detected ocis version https://github.com/owncloud/ocis-php-sdk/pull/229 
     - [x] throw an exception about API endpoint not implemented on ocis version less than 6.0.0 using capabilities api 
- [x] share invite https://github.com/owncloud/ocis-php-sdk/pull/226
- [x] delete share https://github.com/owncloud/ocis-php-sdk/pull/227
- [x] update share https://github.com/owncloud/ocis-php-sdk/pull/230
- [x] https://github.com/owncloud/ocis-php-sdk/pull/232

## Ocis-php-sdk story-line for drive invitation
-  user A invite user B on drive `player`. 
- user A should be able to update the role, and expiration date and remove the user. 
- user B gets invited-drive on  getMYdrive.
- user B should able to get all resources inside invited drive.
- user B should able to invite other user if he/she has enough permission.
- user B should get permission of drive on which he/she invited 

## Test coverage
-  user send drive invitation to group
- user A invite user B on drive `player`. 
- user A should be able to update the role, and expiration date and remove the user. 
- user B gets invited-drive on  getMYdrive.
- user B should able to get all resources inside invited drive.
- user B should able to invite other user if he/she has enough permission.
- user B should get permission of drive on which he/she invited 

- [x] Check ocis-php-sdk with moodle-repository-ocis @nirajacharya2

**Comment by phil-davis** [comment]
The endpoint is available in ocis major version 6, so the code needs to understand that.

**Comment by amrita-shrestha** [comment]
@nirajacharya2 and @SagarGi split tests coverage

**Comment by amrita-shrestha** [comment]
feature support for drive endpoint and tests has been added so closing this issue
