### ISSUE TITLE
setup CI

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis-php-sdk#3]
There are already some tests available (codestyle, phan, php-stan, unit), so we should run them in CI

**Comment by phil-davis** [comment]
I suggest to take a copy of https://github.com/owncloud/activity/blob/master/.drone.star

Delete all the not-relevant sections (acceptance tests etc) and keep the sections for code-style, phan, phpstan, phptests (unit and integration are options in the same `phptests` function).

Then enable the code-style, phan, phpstan and phpunit in the config section.

That should get CI running for all the test pipelines that we have so far.

**Comment by individual-it** [comment]
fixed by #11
