### ISSUE TITLE
naming conventions

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis-php-sdk#62]
what should we call methods that return a set of items?
Currently we have:
- `Ocis::listAllDrives`
- `Ocis::listMyDrives`
- `Ocis::getNotifications`
- `Drive::listResources`

And we are about to add in #55
- `Group::getGroupTypes`
- `Group::getMembers`
- `Ocis::listGroups`

so should it be `get...` or `list...` or maybe even `find..`?

**Comment by phil-davis** [comment]
These things don't "print" output, and I think that "list" has a meaning to "print in output" - like a shopping list.

`get` seems to be the common word for returning information that an object knows - everyone in OOP knows what "a getter" is. `getUrl` `getStatus` etc. - and I think it works fine with plural things `getAllDrives` `getResources` `getGroups` etc.
