### ISSUE TITLE
catch odataerror in create group function

### ISSUE THREAD

**Issue by nirajacharya2** [owncloud/ocis-php-sdk#67]
when we create a group ocis gives `200` status code instead of what's is defined on https://owncloud.dev/libre-graph-api/#/groups/CreateGroup (`201`) 

and the libre graph library only checks for `201`

https://github.com/owncloud/libre-graph-api-php/blob/01c2dfd0e53a1ab13eb6aa184b62c9ba188ff138/lib/Api/GroupsApi.php#L196-L201

so a reminder to add proper error handeling in `createGroup` function

**Comment by amrita-shrestha** [comment]
@nirajacharya2 https://github.com/owncloud/ocis/issues/7678 issue has been closed could you work on this issue
