### ISSUE TITLE
Invalid license ...

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/ocis-php-sdk#78]
![image](https://github.com/owncloud/ocis-php-sdk/assets/1005065/9224ef59-0d74-40e3-bef4-2167b986e0df)

**Comment by individual-it** [comment]
@DeepDiver1975 should be fixed by #81

**Comment by DeepDiver1975** [comment]
THX

**Comment by DeepDiver1975** [comment]
Can you please delete no longer needed branches and rebase all the others?
packagist is reading all branches and because there are too many errors it stops to autoupdate. THX

**Comment by phil-davis** [comment]
I deleted the old branches of PRs that were merged already (somehow the bot had not been automagically removing those in the early days). I pinged others to rebase the 5 PRs currently open.

**Comment by DeepDiver1975** [comment]
There is a setting in the repos to delete merged branches ...

**Comment by DeepDiver1975** [comment]
@phil-davis @individual-it can you please make sure that branches are being rebased asap?
packagist is flooding my mail box .... :see_no_evil:  THX

**Comment by individual-it** [comment]
@DeepDiver1975 should be done

**Comment by DeepDiver1975** [comment]
all clean now - thx
